V0.6.0 dev
stratis-storage/libcryptsetup-rs pull request #228
Opened 2022-08-01 20:34 UTC by jbaublitz

2022-08-08 14:18 UTC, mulkieran approved these changes
The code looks fine to me. It's probably best to run up a stratisd PR against this PR, to verify that resulting API changes can be easily accommodated.

2022-08-08 16:27 UTC, bmr-cymru approved these changes

2022-08-08 17:11 UTC, mulkieran requested changes
Changing to "request changes" category, since it's probably best to put up the stratisd PR before merging, just in case.

2022-08-10 14:02 UTC, mulkieran approved these changes

2022-08-10 21:25 UTC, merged