Add some flags from newer libcryptsetup versions
stratis-storage/libcryptsetup-rs pull request #281
Opened 2023-04-10 01:37 UTC by refi64

This particularly adds the NO_READ/WRITE_WORKQUEUE flags.

2023-04-23 23:05 UTC, refi64 commented
Okay the latest version should work on older versions.

2023-04-28 15:48 UTC, jbaublitz requested changes
Just a couple of things that I'd like to change, but overall this looks good. The feature flagging all looks like it should work based on looking at the cryptsetup 2.3.0 vs 2.4.0 headers. Thanks for doing this!

2023-04-28 15:48 UTC, jbaublitz commented on src/consts/flags.rs
> +        const NO_WRITE_WORKQUEUE = libcryptsetup_rs_sys::crypt_activate_no_write_workqueue;
Would you also mind adding `RECALCULATE_RESET` here flagged as `cryptsetup24supported`? Looking at the header, it looks like that was added too.

2023-05-01 00:57 UTC, refi64 commented on src/consts/flags.rs
> +        const IV_ACTIVATE_LARGE_SECTORS = libcryptsetup_rs_sys::crypt_activate_iv_large_sectors;
oops, ngl not sure why I did that :sweat_smile:

2023-05-01 13:40 UTC, jbaublitz approved these changes

2023-05-01 13:40 UTC, jbaublitz commented
This looks great! Thanks for the contribution.

2023-05-03 18:27 UTC, merged