Prototype of bindgen workaround usage
stratis-storage/libcryptsetup-rs pull request #348
Opened 2024-03-06 03:58 UTC by jbaublitz

Related to rust-lang/rust-bindgen#753

2024-03-08 21:56 UTC, ShayBox commented
Thank you for the first usable workaround for this issue in 7 years.  
I hope to see progress on 753, but this works very well for now.

2024-03-10 02:28 UTC, jbaublitz commented
@ShayBox I would strongly recommend against using it and for waiting until I put up a PR on Github against bindgen. I'm still ironing out some issues with the code so it is not production ready yet, but would love to get anyone's feedback on the code once the PR is up.

2024-03-11 16:55 UTC, jbaublitz commented
@ShayBox You can now follow along with development [here](https://github.com/rust-lang/rust-bindgen/pull/2779).

2024-09-04 13:13 UTC, mulkieran approved these changes

2024-09-04 13:14 UTC, mulkieran commented
Related to https://github.com/stratis-storage/project/issues/713 .

2025-05-05 14:59 UTC, mulkieran requested changes

2025-05-05 14:59 UTC, mulkieran commented on .github/workflows/main.yml
> +      TOOLCHAIN: 1.77.0  # LOWEST SUPPORTED RUST TOOLCHAIN
You can drop the toolchain bumps, they are not necessary now that bindgen rust target is pinned.

2025-05-05 14:59 UTC, mulkieran commented on Cargo.toml
> +rust-version = "1.77.0"  # LOWEST SUPPORTED RUST TOOLCHAIN
Also drop the bump here....

2025-05-06 14:24 UTC, jbaublitz commented
@mulkieran Is this able to be merged?

2025-05-06 18:00 UTC, mulkieran approved these changes

2025-05-06 18:02 UTC, merged